# Generated by Django 5.2 on 2025-05-06 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_delete_kpivalues"),
    ]

    operations = [
        migrations.CreateModel(
            name="KpiValues",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("year", models.IntegerField()),
                ("month", models.IntegerField()),
                ("kpi_value", models.BigIntegerField(null=True)),
                (
                    "kpi",
                    models.ForeignKey(
                        db_column="kpi_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="tasks.kpi",
                    ),
                ),
                (
                    "sub_region",
                    models.ForeignKey(
                        db_column="sub_region_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="tasks.subregions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
